import { StyleSheet, Dimensions } from "react-native";
import { R } from "Resources";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: R.Colors.COLOR_APP_BACKGROUND,
    flex: 1,
  },
  scrollViewStyle: {
    backgroundColor: R.Colors.COLOR_APP_BACKGROUND,
  },
  headerSubTitleStyle: {
    fontSize: 14,
    marginLeft: 10,
    color: R.Colors.COLOR_BLUE,
    fontFamily: "Lato-Regular",
    fontWeight: "500",
  },
  logText: {
    marginTop: 33,
    height: 17,
    flex: 1,
    color: "#929CA5",
    fontFamily: "Lato-Regular",
    fontSize: 14,
    letterSpacing: 0.16,
    lineHeight: 17,
    marginLeft: 16,
  },
  textInputContainer: {
    flexDirection: "row",
    height: 27,
    width: Dimensions.get("window").width - 32,
    backgroundColor: "transparent",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: 6,
    marginLeft: 16,
  },
  textInputStyle: {
    height: 27,
    width: Dimensions.get("window").width - 100,
    color: "#4A586B",
    fontFamily: "Lato-Regular",
    fontSize: 20,
    letterSpacing: 0.22,
    lineHeight: 24,
    padding: 0,
  },
  unitTextStyle: {
    height: 17,
    width: 28,
    color: "#8191A2",
    fontFamily: "Lato-Regular",
    fontSize: 14,
    fontWeight: "500",
    letterSpacing: 0.16,
    lineHeight: 17,
    alignSelf: "flex-end",
    backgroundColor: "transparent",
    textAlign: "right",
  },
  seperatorStyle: {
    marginTop: 4,
    height: 1,
    width: Dimensions.get("window").width - 32,
    backgroundColor: "#e3e7eb",
    marginLeft: 16,
  },
  quickAdd: {
    height: 19,
    width: 76,
    color: "#4A586B",
    fontFamily: "Lato-Regular",
    fontSize: 16,
    letterSpacing: 0.18,
    lineHeight: 19,
    marginTop: 42,
    marginBottom: 12,
    marginLeft: 16,
  },
  quickAddOptionsContainer: {
    height: 125,
    backgroundColor: "transparent",
    width: Dimensions.get("window").width - 20,
    marginLeft: 10,
    marginRight: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  quickAddOptionStyle: {
    backgroundColor: "white",
    width: "23%",
    height: 125,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  waterLevelValue: {
    height: 15,
    color: "#8191A2",
    fontFamily: "Lato-Regular",
    fontSize: 12,
    fontWeight: "500",
    letterSpacing: 0.13,
    lineHeight: 15,
    marginBottom: 18,
    marginTop: 12.5,
  },
  discardButtonStyle: {
    height: 17,
    width: 60,
    color: "#1072E0",
    fontFamily: "Lato-Regular",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 17,
    alignSelf: "center",
  },

  waterIntakeDetailsCardStyle: {
    flexDirection: "row",
    marginTop: 12,
    backgroundColor: "#E1EBF2",
    justifyContent: "space-evenly",
    marginLeft: 16,
    marginRight: 16,
    height: 40,
    borderRadius: 10,
  },
  waterIntakeCardSingleDetailStyle: {
    alignItems: "center",
    flexDirection: "row",
    flex: 1,
    justifyContent: "center",
  },
  waterIntakeCardTitleStyle: {
    fontSize: 12,
  },
  waterIntakeCardDivider: {
    width: 1,
    height: "70%",
    marginTop: 5,
    marginBottom: 5,
    backgroundColor: "#CFDCE5",
  },
});
