import { StyleSheet } from 'react-native';
import { R } from 'Resources';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: R.Colors.COLOR_APP_BACKGROUND,
    justifyContent: 'flex-start',
    // flexDirection: 'column',
    // paddingBottom: 20,
    display: 'flex',
    flex: 1,
  },
  headerContainer: {
    width: '100%',
    marginLeft: 3,
    marginTop: 15,
    fontSize: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  searchIconHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  flatlistContainer: {
    borderWidth: 1,
    borderColor: 'grey',
    marginVertical: 10,
    marginHorizontal: 5,
    backgroundColor: '#fff',
    paddingVertical: 10,
    paddingHorizontal: 30,
  },
  card: {
    borderRadius: 10,
    backgroundColor: 'white',
    shadowColor: R.Colors.COLOR_SHADOW,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    paddingHorizontal: 16,
    paddingVertical: 30,
    margin: 8,
    elevation: 1,
    flexDirection: 'row',
  },
  active: {
    borderBottomColor: R.Colors.COLOR_BLUE_CARDS,
    fontSize: 14,
  },
  tabText: {
    fontSize: 17,
    color: 'rgb(161,170,178)',
    alignItems: 'center',
    textAlign: 'center',
    fontWeight: '400',
  },
  tabWrapper: {
    marginTop: 17,
    borderBottomWidth: 3,
    borderColor: 'transparent',
    paddingBottom: 19,
    flex: 1,
    // paddingHorizontal: 40
  },
  background: {
    backgroundColor: '#fff',
    paddingTop: 20,
    position: 'relative',
    //  paddingHorizontal: 10
  },

  activate: {
    color: R.Colors.COLOR_BLUE_CARDS,
  },
  floatingbutton: {
    position: 'absolute',
    bottom: 30,
    zIndex: 99,
    right: 30,
  },
  wrapper: {
    textAlign: 'center',
    justifyContent: 'center',
    marginVertical: 180,
  },
  emptyText: {
    color: R.Colors.COLOR_CARD_TEXT,
    fontFamily: 'Lato-Regular',
    fontSize: 20,
    fontWeight: 'bold',
    lineHeight: 24,
    textAlign: 'center',
    marginTop: 20,
  },
  emptyTextInfo: {
    color: R.Colors.COLOR_CARD_INFO,
    fontFamily: 'Lato',
    fontSize: 14,
    lineHeight: 17,
    textAlign: 'center',
    paddingHorizontal: 20,
    paddingVertical: 6,
  },
  invitePatient: {
    height: 50,
    width: 222,
    borderRadius: 6,
    backgroundColor: '#CE363E',
    alignSelf: 'center',
    marginTop: 20,
  },
  inviteText: {
    color: '#FFFF',
    fontFamily: 'Lato',
    fontSize: 14,
    fontWeight: 'bold',
    lineHeight: 12,
    textAlign: 'center',
    paddingTop: 20,
  },
  toastSuccessBackGround: {
    backgroundColor: '#96DE4E',
    borderRadius: 26,
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 30,
    paddingRight: 30,
  },
  toastErrorBackGround: {
    backgroundColor: 'red',
    borderRadius: 26,
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 30,
    paddingRight: 30,
  },
  toastText: {
    color: '#FFFFFF',
    fontFamily: 'Lato-Regular',
    fontSize: 14,
    fontWeight: 'bold',
  },
  userIconBkg: {
    height: 40,
    width: 40,
    backgroundColor: R.Colors.COLOR_DARK_BLUE,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },

  userIconText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '600',
  },
});
