export const quotes = [
  'Three months from now you will thank yourself.',
  'Successful weight loss takes programing not willpower.',
  'Only I can change my life, no one can do it for me.',
  'The best project you will ever work on is YOU.',
  'Losing weight is hard. Maintaining weight is hard. Staying overweight is hard. Choose your hard.',
  'The struggle you are in today is developing the strength you need for tomorrow.',
  'You are the designer of your destiny you are the author of your story.',
  'Suffer the pain of discipline or suffering the pain of regret.',
  'All progress takes place outside the comfort zone.',
  'The first step toward success is taken when you refuse to be a captive of the environment in which you find yourself.',
  'If it doesn’t challenge you, it won’t change you.',
  'Food is fuel. Not therapy.',
  'If you’re tired of starting over, stop giving up.',
  'Your body is the baggage you must carry through life. The more excess the baggage, the shorter the trip.',
  'To change your body, you must first change your mind.',
  'Diet is like marriage. You can’t cheat on it and expect it to work.',
  'Success is the sum of small efforts, repeated day in and day out.',
  'I want to see what happens, if I don’t give up.',
  'It takes 4 weeks for you to see your body changing. 8 Weeks for your friends and family to notice. And 12 weeks for the rest of the world to see it. KEEP GOING!',
  'The body achieves what the mind believes.',
  'The chief cause of failure and unhappiness is trading what we want most for that we want in the moment.',
  'If it’s important to you, you will find a way. If not, you will find an excuse.',
  'Don’t wait until you reach your goal to be proud of yourself. You started. Be proud every day.',
  'Be stronger than your excuse.',
  'Eat for the body you want, not for the body you have.',
  'It’s always too soon to quit.',
  'If you wish to grow thinner diminish your dinner.',
  'I still have a long way to go, but I’m already so far from where I used to be and I’m proud of that.',
  'Without discipline, success is impossible, period.',
  'If you keep going you won’t regret it, if you give up you will.',
  'Wake up with determination. Go to bed with satisfaction.',
  'A comfort zone is a beautiful place, but nothing ever grows there.',
  'Do something today that your future self will thank you for.',
  'I am not losing weight. I am getting rid of it. I have no intention of finding it again.',
  'When you are tempted to give up, your breakthrough is probably just around the corner.',
  'Your focus determines your direction.',
  'Don’t be sad because you’re not there yet. Be happy because you’re getting closer every day.',
  'Slow and steady wins the race.',
  'Breaking old habits and forming new ones always takes time. Discipline is never easy but is always worth it in the end.',
  'Don’t reward yourself with food you’re not a dog.',
  'When you feel like quitting, think about why you started.',
  'The difference between who you are and who you want to be is what YOU DO.',
  'Stop beating yourself up. You are work in progress; which means you get there a little at a time, not all at once.',
  'Sacrifice is giving up something good for something better.',
  'Every time you are tempted to react in the same old way, ask if you want to be a prisoner of the past or a pioneer of the future.',
  'If you are facing in the right direction, all you have to do is keep on walking.',
  'Dear stomach, you’re bored not hungry. So, shut up!',
  'At the end of the day, let there be no excuses, no explanations, no regrets.',
  'Junk food you crave for an hour or the body you crave for a lifetime.',
  'I may not be there yet, but I am closer than I was yesterday.',
  'Strive for progress, not perfection.',
  'If you are not in the process of becoming the person you want to be, you are automatically engaged in becoming the person you don’t want to be.',
  'If I quit now, I will soon be back to where I started and when I started, I was desperate to be where I am now.',
  'Not everyone will understand your journey. That’s fine. It’s not their journey to make sense of .It’s yours.',
  'Success is the sum of small efforts, repeated day in and day out.',
  'We all make choices, but in the end our choices make us.',
  'Dieting is the only game where you win when you lose.',
  'If you take care of your body, it will take care of you.',
  'Every day do something that will inch you closer to a better tomorrow.',
  'I’m not a product of my circumstances I’m a product of my decisions.',
  'To get through the hardest journey we need take only one step at a time, but we must keep on stepping.',
  'Don’t erase all your hard work this week, just because it’s the weekend.',
  'Everyone must choose one of two pains: The pain of discipline or the pain of regret.',
  'For many years of my life, by choice, I weighed over 200 lbs. I say by choice because I have never accidentally eaten anything.',
  'Without a struggle there can be no progress.',
  'People often say that motivation doesn’t last, but neither does bathing. That’s why we recommend it daily.',
  'If you do what you always did, you will get what you always got.',
  'It’s not about perfect. It’s about effort. And when you bring that effort every single day, that’s where transformation happens. That’s how change occurs.',
  'Nothing tastes as good as being thin feels.',
  'A man too busy to take care of his health, is like a mechanic too busy to take care of his tools.',
  'Eat like your life depends on it, because it does.',
  'If you think the pursuit of good health is expensive and time consuming. Try illness.',
  'To lengthen your life, shorten your meals.',
  'With the wrong diet no medicine can help, with the right diet no medicine is necessary.',
  'It’s not a diet, it’s a lifestyle change.',
  'If you don’t do what’s best for your body, you’re the one who comes up on the short end.',
  'It’s not just about losing the weight. It’s about losing the lifestyle and mindset that got you there.',
  'Take care of your body. It’s the only place you have to live.',
  'One should eat to live, not live to eat.',
  'Looking after my health today gives a better hope for tomorrow.',
  'You will never change your life until you change something you do daily. The secret of your success is found in your daily routine.',
  'One way to keep momentum going is to have constantly greater goals.',
  'Health is not about the weight you lose but about the life you gain.',
  'Virtually everything we do inlife is a matter of habit. Habits make us who we are, make a healthy lifestyle your hobby.'
];
